# Generated by Django 3.0.1 on 2019-12-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20191222_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='brand',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
