# Generated by Django 3.0.1 on 2019-12-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20191220_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='brand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
