# Generated by Django 3.0.1 on 2019-12-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20191222_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='categories',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
